name: Build Python

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-python.yml'
      - 'wrappers/**'
      - 'src/**'
      - 'include/**'
      - 'example/**'
      - 'CMakeLists.txt'

jobs:
  build-linux:
    uses: ./.github/workflows/build-linux.yml
    secrets: inherit

  build-macos:
    uses: ./.github/workflows/build-macos.yml
    secrets: inherit

  build-windows:
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit

  build-python:
    needs: 
        - build-linux
        - build-windows
        - build-macos
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
    
      - name: Download Linux Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-x86_64
          path: linux

      - name: Download Windows Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-x86_64
          path: windows

      - name: Download macOS Universal Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-universal
          path: macos

      - name: Create Build Directories
        run: |
            mkdir -p build/linux
            mkdir -p build/windows
            mkdir -p build/macos
            mkdir -p build/models

      - name: Copy Linux Build Artifacts
        run: cp -r linux/* build/linux

      - name: Copy Windows Build Artifacts
        run: cp -r windows/* build/windows

      - name: Copy macOS Universal Build Artifacts
        run: cp -r macos/* build/macos

      - name: Copy Models
        run: cp -r models/* build/models

      - name: Copy Python Wrapper
        run: cp wrappers/babylon.py build/__init__.py

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
            name: python
            path: build/
